// export default function data() {
//   return [
//     {
//       id: 0,
//       src: "./src/img/images/catnip.png",
//       title: "Spark Man",
//       alt: "",
//       desc: "",
//       thumb: "./src/img/images/catnip.png",
//     },
//     {
//       id: 1,
//       src: "./src/img/images/bone-orb.webp",
//       title: "Snake Man",
//       alt: "",
//       desc: "",
//       thumb: "./src/img/images/bone-orb.webp",
//     },
//     {
//       id: 2,
//       src: "./src/img/images/bony-steve.webp",
//       title: "Needle Man",
//       alt: "",
//       desc: "",
//       thumb: "./src/img/images/bony-steve.webp",
//     },
//     {
//       id: 3,
//       src: "./src/img/images/youre boned.webp",
//       title: "Hard Man",
//       alt: "",
//       desc: "",
//       thumb: "./src/img/images/youre boned.webp",
//     },
//     {
//       id: 4,
//       src: "./src/img/images/bone-orb2.webp",
//       title: "mega man",
//       alt: "",
//       desc: "",
//       thumb: "./src/img/images/bone-orb2.webp",
//     },
//     {
//       id: 5,
//       src: "./src/img/images/bony-steve.webp",
//       title: "Top Man",
//       alt: "",
//       desc: "",
//       thumb: "./src/img/images/bony-steve.webp",
//     },
//     {
//       id: 6,
//       src: "./src/img/images/youre boned.webp",
//       title: "Gemini Man",
//       alt: "",
//       desc: "",
//       thumb: "./src/img/images/youre boned.webp",
//     },
//     {
//       id: 7,
//       src: "./src/img/robits/magnet-man.png",
//       title: "Magnet Man",
//       alt: "",
//       desc: "",
//       thumb: "./src/img/robits/magnet-man.png",
//     },
//     {
//       id: 8,
//       src: "./src/img/robits/shadow-man.png",
//       title: "Shadow Man",
//       alt: "",
//       desc: "",
//       thumb: "./src/img/robits/shadow-man.png",
//     },
//     {
//       id: 9,
//       src: "./src/img/images/paw.png",
//       title: "",
//       alt: "",
//       desc: "",
//       thumb: "./src/images/img/paw.png",
//     },
//   ];
// }

export default function data() {
  return [
    {
      id: 0,
      src: "https://msnicelupe.neocities.org/img/cats/mitsy1.gif",
      title: "mitsy the cat",
      alt: "mitsy, a grey and white cat, is resting.",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/mitsy1.gif",
    },
    {
      id: 1,
      src: "https://msnicelupe.neocities.org/img/cats/mitsy2.gif",
      title: "mitsy the cat",
      alt: "mitsy is looming over the camera",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/mitsy2.gif",
    },
    {
      id: 2,
      src: "https://msnicelupe.neocities.org/img/cats/max1.gif",
      title: "max the cat",
      alt: "max, a black and white cat, sits up patiently looking at the camera",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/max1.gif",
    },
    {
      id: 3,
      src: "https://msnicelupe.neocities.org/img/cats/zim2.gif",
      title: "zimmerman the cat",
      alt: "zimmerman, a toasted marshmallow cat, is sleeping soundly",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/zim2.gif",
    },
    {
      id: 4,
      src: "https://msnicelupe.neocities.org/img/cats/zim1.gif",
      title: "zimmerman the cat",
      alt: "zimmerman the cat is peering into the camera",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/zim1.gif",
    },
    {
      id: 5,
      src: "https://msnicelupe.neocities.org/img/cats/tizzy1.gif",
      title: "tiswas the cat",
      alt: "tizzy, a black and white cat, is lying on her front on a chair and looking left of camera",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/tizzy1.gif",
    },
    {
      id: 6,
      src: "https://msnicelupe.neocities.org/img/cats/zim3.gif",
      title: "zimmerman the cat",
      alt: "zimmerman the cat is walking toward the camera",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/zim3.gif",
    },
    {
      id: 7,
      src: "https://msnicelupe.neocities.org/img/cats/timmy2.gif",
      title: "timmy the cat",
      alt: "timothy, a white and ginger cat, is sitting and watching",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/timmy2.gif",
    },
    {
      id: 8,
      src: "https://msnicelupe.neocities.org/img/cats/tommy1.gif",
      title: "tommy the cat",
      alt: "thomas, timmy's ginger and white brother, leans to camera",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/tommy1.gif",
    },
    {
      id: 9,
      src: "https://msnicelupe.neocities.org/img/cats/nelson2.gif",
      title: "nelson the cat",
      alt: "nelson, a russian blue mix cat, sleeps.",
      desc: "",
      thumb: "https://msnicelupe.neocities.org/img/cats/nelson2.gif",
    },
  ];
}
