export default function data() {
  return [
    {
      id: 0,
      src: "./src/img/images/catnip.png",
      title: "Spark Man",
      alt: "",
      desc: "",
      thumb: "./src/img/images/catnip.png",
    },
    {
      id: 1,
      src: "./src/img/images/bone-orb.webp",
      title: "Snake Man",
      alt: "",
      desc: "",
      thumb: "./src/img/images/bone-orb.webp",
    },
    {
      id: 2,
      src: "./src/img/images/bony-steve.webp",
      title: "Needle Man",
      alt: "",
      desc: "",
      thumb: "./src/img/images/bony-steve.webp",
    },
    {
      id: 3,
      src: "./src/img/images/youre boned.webp",
      title: "Hard Man",
      alt: "",
      desc: "",
      thumb: "./src/img/images/youre boned.webp",
    },
    {
      id: 4,
      src: "./src/img/images/bone-orb2.webp",
      title: "mega man",
      alt: "",
      desc: "",
      thumb: "./src/img/images/bone-orb2.webp",
    },
    {
      id: 5,
      src: "./src/img/images/bony-steve.webp",
      title: "Top Man",
      alt: "",
      desc: "",
      thumb: "./src/img/images/bony-steve.webp",
    },
    {
      id: 6,
      src: "./src/img/images/youre boned.webp",
      title: "Gemini Man",
      alt: "",
      desc: "",
      thumb: "./src/img/images/youre boned.webp",
    },
    {
      id: 7,
      src: "./src/img/robits/magnet-man.png",
      title: "Magnet Man",
      alt: "",
      desc: "",
      thumb: "./src/img/robits/magnet-man.png",
    },
    {
      id: 8,
      src: "./src/img/robits/shadow-man.png",
      title: "Shadow Man",
      alt: "",
      desc: "",
      thumb: "./src/img/robits/shadow-man.png",
    },
    {
      id: 9,
      src: "./src/img/images/paw.png",
      title: "",
      alt: "",
      desc: "",
      thumb: "./src/images/img/paw.png",
    },
  ];
}
